{{- if and .Values.admin.password (not .Values.admin.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlist.adminSecretName" . }}
  namespace: {{ include "openlist.namespace" . }}
  labels:
    {{- include "openlist.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENLIST_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
{{- end }}
